using JobManagement.Domain.Identifiers;

namespace JobManagement.Abstractions.Persistence;

/// <summary>
///     Represents a lease for a dequeued job. A lease prevents other workers from processing the same job.
/// </summary>
public sealed record JobLease
{
    /// <summary>
    ///     Gets The leased job id.
    /// </summary>
    public JobId JobId { get; init; }

    /// <summary>
    ///     Gets Lease token (opaque string generated by the store).
    ///     Gets The store must validate this token on renew/complete/fail.
    /// </summary>
    public string LeaseToken { get; init; } = string.Empty;

    /// <summary>
    ///     Gets Worker id that owns this lease (provided by the engine/host).
    /// </summary>
    public string WorkerId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets UTC time when the lease expires.
    /// </summary>
    public DateTimeOffset ExpiresAtUtc { get; init; }

    /// <summary>
    ///     Gets Returns true if the lease is expired at the provided time.
    /// </summary>
    /// <returns>Return Expired Boolean. </returns>
    public bool IsExpired(DateTimeOffset nowUtc)
    {
        return nowUtc >= ExpiresAtUtc;
    }
}